export const categories = [
  { value: "clothing", label: "Clothing & Fashion" },
  { value: "jewelry", label: "Jewelry & Accessories" },
  { value: "home_decor", label: "Home Decor" },
  { value: "art", label: "Art & Collectibles" },
  { value: "toys", label: "Toys & Games" },
  { value: "craft_supplies", label: "Craft Supplies & Tools" },
  { value: "weddings", label: "Weddings & Parties" },
  { value: "bags", label: "Bags & Purses" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "stationery", label: "Stationery & Office" },
  { value: "vintage", label: "Vintage Items" },
  { value: "furniture", label: "Furniture & Woodwork" },
  { value: "ceramics", label: "Ceramics & Pottery" },
  { value: "candles", label: "Candles & Aromatherapy" },
  { value: "bath", label: "Bath & Body" },
  { value: "knitting", label: "Knitting & Crochet" },
  { value: "leather", label: "Leather Goods" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "digital", label: "Digital Downloads" },
  { value: "food", label: "Homemade Food & Treats" },
  { value: "plants", label: "Plants & Gardening" },
  { value: "glass", label: "Glass Art" },
  { value: "seasonal", label: "Seasonal & Holiday Items" },
  { value: "calligraphy", label: "Calligraphy & Lettering" },
  { value: "metalwork", label: "Metal Work" },
];
