
"use client";
import { useEffect, useState } from "react";

export default function Home() {
  const sections = [
    { id: "section1", title: "Bingo's Role" },
    { id: "section2", title: "IP Reports" },
    { id: "section3", title: "Counter Notices" },
    { id: "section4", title: "Repeat Infringement" },
    { id: "section5", title: "Withdrawals" },
    

   
  ];

  const [activeId, setActiveId] = useState<string>("");

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        const visibleSection = entries.find((entry) => entry.isIntersecting);
        if (visibleSection) {
          setActiveId(visibleSection.target.id);
        }
      },
      { rootMargin: "-50% 0px -50% 0px", threshold: 0 }
    );

    sections.forEach((item) => {
      const el = document.getElementById(item.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  return (
    <div className="flex">
      
     <nav className="fixed left-0 top-30 w-[21%] p-4 rounded-lg  h-screen ">
        <h3 className="font-bold mb-3 text-2xl text-gray-700">Contents</h3>
        <ul className="space-y-2">
        
          {sections.map((item) => (
  <li key={item.id}>
    <a
      href={`#${item.id}`}
      className={`block px-1 py-2 rounded-lg transition-all duration-300 ${
        activeId === item.id
          ? "bg-gray-200 text-orange-600 font-bold shadow-md scale-105"
          : "text-gray-700 hover:text-orange-600 hover:bg-gray-100"
      }`}
    >
      <div className="flex items-center gap-3">
        <div
          className={`w-2 h-2 rounded-full transition-all duration-300 ${
            activeId === item.id ? "bg-orange-600" : "bg-gray-400"
          }`}
        ></div>
        <span >{item.title}</span>
      </div>
    </a>
  </li>
))}

        </ul>
      </nav>

     
      <main className="ml-[300px] p-8 space-y-8 scroll-smooth">
        <img src="/assets/Intellectual policies.jpg" alt="" className="w-[100%] h-[12%] rounded-lg " />
     {/* <div className="bg-[url('/assets/polices_homepage.webp')] bg-cover bg-center w-[100%] h-96 rounded-lg shadow-lg mb-8 flex flex-col items-start justify-center gap-10"> */}
  <h1 className="text-[80px] text-white font-bold drop-shadow-lg ml-20"></h1> 
 <div> <p className="text-gray-400 ml-20 "><span className="text-white"></span></p>
 {/* </div> */}

</div>
<section className="pb-[80px]">
   <h1 className="text-gray-700 font-bold text-[32px]">Intellectual policies</h1> 

   <p className="text-gray-500 text-[16px] ml-4">As a venue for artists, designers, and makers, Bingo takes intellectual property rights very seriously. We comply with intellectual property laws and industry best practices in order to maintain the integrity of our creative marketplace. This Intellectual Property Policy explains how we address allegations of infringement, how authorized parties can submit reports of infringement regarding content on our marketplace, and how Bingo sellers can respond when their listings or shops are affected by a report.</p><br />
<strong className="text-gray-700 ml-4  font-bold text-[18px]">This policy is a part of our Terms of Use.</strong><br />
<ul className="list-decimal pl-5 space-y-1 text-gray-500 mt-2 ml-8">
<li>Bingo's Role</li>
<li>Reports of Intellectual Property Infringement</li> 
<li>Counter Notices</li>
<li> Repeat Infringement</li>
<li> Withdrawals</li>
</ul>
    
</section>
{/* section1 */}
        <section id="section1" className="pt-[150px]">
          <h2 className="text-2xl font-bold mb-4 text-gray-700">Bingo's Role</h2>
         <p className="text-gray-500 text-[16px] ml-4">-Bingo is a marketplace comprised of individual third¬-party sellers who run their own shops, create their own policies, and are responsible for their<br />   &nbsp;&nbsp; inventory, shipments, and complying with the law. We provide a venue, but Bingo does not manufacture goods, hold inventory, or ship items on<br />   &nbsp;&nbsp; behalf of our sellers. The content uploaded on Bingo's marketplace is generated by independent sellers who are not employees, agents, or<br />   &nbsp;&nbsp; representatives of Bingo. Sellers are responsible for ensuring they have all necessary rights to their content and that they are not infringing <br />   &nbsp;&nbsp;&nbsp;or violating any third party’s rights by posting it.</p><br/>
         <p className="text-gray-500 text-[16px] ml-4">-Bingo reserves the right to disable any listing, shop, or account that we believe violates our Terms of Use, including this Intellectual Property Policy <br />&nbsp;&nbsp;or our Prohibited Items Policy. Bingo also reserves the right to take action against abusers of Bingo’s Intellectual Property Policy or our Terms of Use.</p><br/>
        <p className="text-gray-500 text-[16px] ml-4">-Bingo can’t speak on behalf of intellectual property owners, nor is Bingo in a position to offer legal advice or make legal determinations whether <br />&nbsp;&nbsp; a shop’s content infringes someone else’s intellectual property. Bingo will remove material cited for alleged intellectual property infringement  <br />&nbsp;&nbsp;&nbsp;when provided with a report that complies with our policies.</p>
        </section>
{/* section2 */}
   <section id="section2" className="pt-[150px]">
          <h2 className="text-2xl font-bold mb-4 text-gray-700">Reports of Intellectual Property Infringement</h2>
       
  <p className="text-gray-500 text-[16px] ml-4">-Bingo strives to respond quickly when we receive a report of intellectual property infringement that complies with our policies by removing or disabling <br />&nbsp;&nbsp;access to the allegedly infringing material. When Bingo removes or disables access in response to a report, Bingo makes a reasonable attempt to <br />&nbsp;&nbsp;contact the affected member, provide information about the report and removal, and, in cases of alleged copyright infringement, provide information <br />&nbsp;&nbsp;about how to submit a counter notice. Bingo may also provide a copy of the infringement report, including the name and email address of the reporting<br />&nbsp;&nbsp; party, to the affected member.</p><br/>
<p className="text-gray-500 text-[16px] ml-4">-To submit a report of alleged infringement against Bingo shop listings, you can use the Bingo Reporting Portal. This is the easiest way to report alleged <br />&nbsp;&nbsp;infringement to Bingo and its Designated Agent under the Digital Millennium Copyright Act and other intellectual property rights.</p><br/>
<p className="text-gray-500 text-[16px] ml-4">-To submit a report of alleged infringement against usernames, shop names, videos on an Bingo shop page, or videos from an Explore post on Bingo,<br />&nbsp;&nbsp; use Bingo’s Reporting Form.
If you are unable to use the Bingo Reporting Portal, you can read more about our DMCA notice requirements and  <br />&nbsp;&nbsp;Designated Agent here.
</p><br />
<p className="text-gray-500 text-[16px] ml-4">-Bingo may request additional information before processing a report, such as a letter of authorization from the rights owner, identity verification of the<br />&nbsp;&nbsp; reporting party, or other documentation regarding the claimed right. Bingo may reject reports of infringement or counter notices that contain <br />&nbsp;&nbsp; information we believe is false, fraudulent, incomplete, or otherwise submitted in bad faith. Bingo also reserves the right to take action against abusers of <br />&nbsp;&nbsp;&nbsp;this policy.</p>
     

        </section>
        {/* section3 */}
        <section id="section3" className="pt-[150px]">
          <h2 className="text-2xl font-bold mb-4 text-gray-700">Counter Notice</h2>
        <p className="text-gray-500 text-[16px] ml-4">-In accordance with the Digital Millennium Copyright Act (DMCA), Bingo accepts counter notices for Egyptian-based copyright infringement reports only.<br />&nbsp;&nbsp; When Bingo receives a DMCA counter notice, we will provide a copy of the counter notice to the original complaining party. The removed material may<br />&nbsp;&nbsp; be replaced or access to it may be restored 10 business days after the counter notice is processed, unless the copyright owner files an action seeking a <br />&nbsp;&nbsp;&nbsp;court order restraining the allegedly infringing party from relisting the items or a qualifying action with the Copyright Claims Board (CCB), and informs<br />&nbsp;&nbsp; Bingo of this action. Read more about DMCA notices, counter notices, and requirements here.</p>
       


        

        </section>
   {/* section4 */}
    <section id="section4" className="pt-[150px]">
          <h2 className="text-2xl font-bold mb-4 text-gray-700">Repeat Infringement</h2>
       <p className="text-gray-500 text-[16px] ml-4">-Bingo terminates selling privileges of members who are subject to repeat or multiple notices of intellectual property infringement in appropriate<br />&nbsp;&nbsp; circumstances and at Bingo’s discretion. If we believe a member has attempted to open a new shop after termination of the initial account, we reserve <br />&nbsp;&nbsp;&nbsp;the right to refuse all services to that member. These actions apply to any accounts we believe are associated with or operated by the affected member.<br />&nbsp;&nbsp; Per our Terms of Use, Bingo reserves the right to terminate account privileges at any time, for any reason, and without advance notice.</p>
        </section>

        {/* section5 */}
         <section id="section5" className="pt-[150px]">
          <h2 className="text-2xl font-bold mb-4 text-gray-700">Withdrawals</h2>
       <p className="text-gray-500 text-[16px] ml-4">-Bingo only accepts withdrawals of infringement reports directly from the intellectual property owner or authorized representative who submitted the<br />&nbsp;&nbsp; claim. The withdrawal must clearly state that it is a formal withdrawal and sufficiently identify the member and/or material (such as by providing the <br />&nbsp;&nbsp; username, shop name, and Bingo listing URLs).</p><br/>
       <p className="text-gray-500 text-[16px] ml-4">-Once Bingo receives a formal withdrawal of an infringement report, Bingo will contact the withdrawing party to confirm receipt and will notify the affected  <br />&nbsp;&nbsp;member of the withdrawal. Please note that infringement matters are reviewed on a case-by-case basis, and withdrawals do not guarantee changes to a<br />&nbsp;&nbsp; member's shop status.</p>
        </section>
     
      
      </main>
    </div>
  );
}
