import "./global.css";
import Providers from "./provider";
import AuthGuard from "../shared/components/AuthGuard";

export const metadata = {
  title: "Bingo Seller",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen font-sans antialiased`}
        suppressHydrationWarning={true}
      >
        <Providers>
          <AuthGuard>{children}</AuthGuard>
        </Providers>
      </body>
    </html>
  );
}
