import './global.css';
import Providers from './provider';
import {Poppins} from "next/font/google"
import ClientRestrictionWrapper from "../shared/components/ClientRestrictionWrapper";

export const metadata = {
  title: 'Bingo Seller',
  description: 'Generated by create-nx-workspace',
}

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable:"--font-poppins",
  display: "swap",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen font-sans  antialiased ${poppins.variable}`}>
        <Providers>
          <ClientRestrictionWrapper>
            {children}
          </ClientRestrictionWrapper>
        </Providers>
        
      </body>
    </html>
  )
}
