export const categoryImageMap: Record<string, string> = {
  "Jewelry": "/assets/categories/Jewelry.png",
  "Clothing": "/assets/categories/Jewelry.png",
  "HomeDecor": "/assets/categories/Jewelry.png",
  "Art": "/assets/categories/Jewelry.png",
  "Toys": "/assets/categories/Jewelry.png",
  "Accessories": "/assets/categories/Jewelry.png",
  "Bags": "/assets/categories/Jewelry.png",
  "Ceramics": "/assets/categories/Jewelry.png",
  "Woodwork": "/assets/categories/Jewelry.png",
  "Knitting": "/assets/categories/Jewelry.png",
  "Craft Supplies & Tools": "/assets/categories/craft-supplies.png",
  "Home & Hobby": "/assets/categories/home-hobby.png",
  "Sewing & Fiber": "/assets/categories/sewing-fiber.png",
  "Jewelry & Beauty": "/assets/categories/jewelry-beauty.png",
  "Visual Arts": "/assets/categories/visual-arts.png",
  "Paper, Party & Kids": "/assets/categories/paper-party-kids.png",
  "Sculpting & Forming": "/assets/categories/sculpting-forming.png",
};
